### ISSUE TITLE
About the location of the Kernel file

### ISSUE THREAD

**Issue by crcms** [ibrunotome/laravel-api-templates#10]
Hello
I don't quite understand, in my opinion, Kernel, shouldn't it belong to the Application layer? It provides the environmental mechanism of the current application
Interface is just dealing with the user interface.

**Comment by ibrunotome** [comment]
Makes sense. I intend to update the project in the next few weeks and this will be changed. Or you can make a PR.

**Comment by crcms** [comment]
Submitted PR
