### ISSUE TITLE
where the route files?

### ISSUE THREAD

**Issue by IgorDePaula** [ibrunotome/laravel-api-templates#16]

**Comment by ibrunotome** [comment]
- default: https://github.com/ibrunotome/laravel-api-templates/tree/master/default-structure/routes
- modular: https://github.com/ibrunotome/laravel-api-templates/blob/master/modular-structure/app/Domain/Users/Providers/RouteServiceProvider.php

**Comment by IgorDePaula** [comment]
Thank you, I finish your medium article and already know.

Thank you for your attention.
